- name: docker task
  hosts: all
  become: true
  become_user: root
  
  tasks:
   - name: Upgrade all apt packages
     apt: upgrade=dist force_apt_get=yes
      
   - name: install docker
     apt:
       name: docker-ce
       state: latest
       update_cache: true
   - name: Start docker service
     service:
       name: docker
       state: started
