- name: docker task
  hosts: all
  become: true
  
  tasks:
   - name: install docker
     apt: 
       package: docker-ce
       state: latest
   - name: Start docker service
     service:
       name: docker
       state: started
