- name: docker task
  hosts: all
  become: true
  become_user: root
  
  tasks:
   - name: install docker
     apt:
       name: docker.io
       state: latest
       
   - name: Start docker service
     service:
       name: docker
       state: started
