- name: docker task
  hosts: all
  become: true
  become_user: root
  
  tasks:
   - name: Upgrade all apt packages
     apt: 
       upgrade: dist
       update_cache: yes
       dpkg_options: 'force-confold,force-confdef'
      
   - name: install docker
     apt:
       name: docker.io
       state: latest
       update_cache: true
   - name: Start docker service
     service:
       name: docker
       state: started
